# Generated by Django 3.0.7 on 2020-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('open', models.CharField(max_length=15)),
                ('bill_no', models.IntegerField()),
                ('bale_no', models.IntegerField()),
                ('party_name', models.CharField(max_length=30)),
                ('party_quality_name', models.CharField(max_length=30)),
                ('our_quality_name', models.CharField(max_length=30)),
                ('hsn_code', models.CharField(max_length=20)),
                ('taka', models.IntegerField()),
                ('mts', models.CharField(max_length=10)),
                ('Description', models.CharField(blank=True, max_length=300)),
                ('shortage', models.CharField(max_length=10)),
            ],
        ),
    ]
