# Generated by Django 3.0.7 on 2020-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Description',
        ),
    ]
