# Generated by Django 3.0.7 on 2020-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0002_remove_purchase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='design',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
