# Generated by Django 3.0.7 on 2020-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0003_purchase_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='design',
            field=models.CharField(max_length=20),
        ),
    ]
