# Generated by Django 3.0.7 on 2020-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0004_auto_20200612_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='design',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
