# Generated by Django 3.0.7 on 2020-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0005_auto_20200612_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyer_name', models.CharField(max_length=30)),
                ('bale_no', models.IntegerField()),
                ('our_quality_name', models.CharField(max_length=30)),
                ('design', models.CharField(blank=True, max_length=20)),
                ('taka', models.IntegerField()),
                ('mts', models.FloatField()),
            ],
        ),
    ]
