# Generated by Django 3.0.7 on 2020-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0006_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mts_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='taka_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
